version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
        name: NPM Install
        command: npm install
      - run:
        name: Test
        command: npm test